---
title: "Chapter 4"
author: "Philipp Grafendorfer"
date: "15 März 2018"
output: html_document
---

```{r setup, include=FALSE}
library(rethinking)
knitr::opts_chunk$set(echo = TRUE)
```

##4M1
```{r}
# plot the prior
curve(dnorm(x, 0, 10), from = -30, to = 30)
```

```{r}
curve(dunif(x, 0, 10), from = -5, to = 15)
```

```{r}
# simulate observed y- values from the prior
sample_mu <- rnorm(1e4, 0, 10)
sample_sigma <- runif(1e4, 0, 10)
prior_y <- rnorm(1e4, mean = sample_mu, sd = sample_sigma)
dens(prior_y)
```

```{r}
flist <- alist(
  height ~ dnorm(mu, sigma),
  mu ~ dnorm(10, 0),
  sigma ~ dunif(0, 10)
)

m4.1 <- map(flist, data)
```

## 4H1
```{r}
library(rethinking)
data("Howell1")
d <- Howell1
d2 <- d[d$age >= 18,]
```

Fit the model and sum up the resulting parameters.
```{r}
m4.2 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b*weight,
    a ~ dnorm(156, 100),
    b ~ dnorm(0, 10),
    sigma ~ dunif(0, 50)
  ),
  data = d2
)
precis(m4.2, corr = T)
```

Sample from the posterior distribution
```{r}
post <- extract.samples(m4.2)
post[1:10,]
```

The link function
```{r}
mu <- link(m4.2)
```


make the prediction
```{r}
weight.seq <- c(46.95, 43.72, 64.78, 32.59, 54.63)
mu <- link(m4.2, data = data.frame(weight = weight.seq))
str(mu)
```

```{r}
# use type="n" to hide raw data 4.55
plot( height ~ weight , d2 , type = "n" )
# loop over samples and plot each mu value
for (i in 1:100 )
points( weight.seq , mu[i,] , pch = 16 , col = col.alpha(rangi2,0.1) )
```

```{r}
(weight.seq)
(mu.mean <- apply(mu, 2, mean))
(mu.HPDI <- apply(mu, 2, HPDI, prob = 0.89))
```

## 4H2
```{r}
d3 <- d[d$age < 18,]
m4.3 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b*weight,
    a ~ dnorm(200, 100),
    b ~ dnorm(2.72, 0.07),
    sigma ~ dunif(0, 10)
  ),
  data = d3
)
precis(m4.3, corr = T)
```

```{r}
mu <- link(m4.3)
mu.HPDI <- apply(mu, 2, HPDI)
mu.mean <- apply(mu, 2 , mean)
sim.height <- sim(m4.3, data = list(weight = d3$weight))
height.PI <- apply(sim.height, 2, PI, prob = 0.89)

plot(height ~ weight, data = d3, col = col.alpha(rangi2,0.7))
abline(a = coef(m4.3)["a"], b = coef(m4.3)["b"])
shade(mu.HPDI, d3$weight) # one cant even see that
shade(height.PI, d3$weight)
```

## 4H3

```{r}
m4.4 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- alpha + beta*log(weight),
    alpha ~ dnorm(178, 100),
    beta ~ dnorm(0, 100),
    sigma ~ dunif(0, 50)
  ),
  data = d
)
precis(m4.4, corr = T)
```

```{r}
plot(height ~ log(weight), data = d, col = col.alpha(rangi2,0.8))
```

One could have expected that the result will be linear. so now the linear regression will fit quite nicely.

```{r}
post <- extract.samples(m4.4)
weight.seq <- seq(from=1, to=100, length.out = 100)

# modelling of mu:
mu.link <- function(weight) post$alpha + post$beta * log(weight)
mu <- sapply(X = weight.seq,  FUN = mu.link)
mu.mean <- apply(mu, 2, mean)
mu.HPDI <- apply(mu, 2, HPDI, prob = 0.89)

# simulate heights and compute HPDI
height.link <- function(weight) rnorm(n = nrow(post), mean = mu.link(weight), sd = post$sigma)
height.samples <- sapply(X = weight.seq, FUN = height.link)
height.hpdi <- apply(X = height.samples, MARGIN = 2, FUN = HPDI, prob = .89)

#plot
plot(height ~ weight, data = d, col = col.alpha(rangi2, .4))
lines(x = weight.seq, y = mu.mean)
shade(object = mu.HPDI, lim = weight.seq)
shade(object = height.hpdi, lim = weight.seq)
```




